---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop-jumpbox
  namespace: default
  labels:
    app: webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      labels:
        app: webtop
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
          ports:
            - containerPort: 3001
              name: https
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - name: webtop-config
              mountPath: /config
      volumes:
        - name: webtop-config
          persistentVolumeClaim:
            claimName: webtop-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: webtop-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: webtop
  ports:
    - name: https
      port: 3001
      targetPort: 3001
      nodePort: 30000
