---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webtop-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtop-jumpbox
  namespace: default
  labels:
    app: webtop
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: webtop
  template:
    metadata:
      labels:
        app: webtop
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: webtop
          image: lscr.io/linuxserver/webtop:alpine-icewm-version-728f016d
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: webtop-config
              mountPath: /config
            - name: tmp
              mountPath: /tmp
            - name: var-run
              mountPath: /var/run
      volumes:
        - name: webtop-config
          persistentVolumeClaim:
            claimName: webtop-config-pvc
        - name: tmp
          emptyDir: {}
        - name: var-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webtop-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: webtop
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtop-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure # À adapter selon ta config Traefik
spec:
  rules:
  - host: webtop.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webtop-svc
            port:
              number: 3000