keys:
  - &master_key age1qmlxfhscaexxqeaw59aqc66r2qce2suxge537pm7rtc8w7glp98s9xgny7
  - &worker_key age1vwws3rm6j6rxjellnj30e2lunu72sfhr36j0zgzvu9jjup63wpfs9aq2gc

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *master_key
          - *worker_key
