keys:
  - &master_key age1qmlxfhscaexxqeaw59aqc66r2qce2suxge537pm7rtc8w7glp98s9xgny7
  - &worker_key age103m56fylzmgf4j39kxnvyn0tarfxvtzmfxafj227pxn43z0rcgtqnfgfpz

creation_rules:
  - path_regex: (secrets\.yaml|.*-sops\.yaml)$
    key_groups:
      - age:
          - *master_key
          - *worker_key
