apiVersion: ENC[AES256_GCM,data:ANg=,iv:p0RPgNRLrqq5pqaSRTNgEUTySHnNfVSzBrzwj56D4hI=,tag:iH9f+ZWPmMNtETh13snaVw==,type:str]
data:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:VwJ9ftIn/Mopi5EshOAlZkKWuiFDiuiD4N+ykn1EZdrDxNePAsJOQazZz4rjVaLkifMWIFDI4Kv1rGsQ,iv:a9F8Gji2pN5+Vq5BfN0S89Fbq/WbVHFPzY/l/fwe/4s=,tag:/9IpQAfw62f8cSR7zmlHeQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:f3H9WnyrWlYWNLUClP+8CQ==,iv:i9w0zI02Lkfg7W5X0hdhXoVx8t9uPP6+PxwSMr2sQ9Q=,tag:D92RqW2GuOrbTNdcksMF2A==,type:str]
kind: ENC[AES256_GCM,data:Q1+Adzww,iv:TgczZGiYNlBXulXPYxzkT7bC+WKIHWA59gkh2jUNtpw=,tag:Z0OihVmohs9V6ssIctXMwA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:DdIlegvTNRLJMNXefg==,iv:ph7RS6yt1VkJVddZoZKpH9tfsb4avtTbDo9TxidrsZ8=,tag:TDE7hYN5G6ErmpCbtDYcZw==,type:str]
    namespace: ENC[AES256_GCM,data:lW0R93ElpQ==,iv:ggpFu+OEaoY3Ta64MOl6Yu4vVjdFNLZbnLwDSjx8KMk=,tag:kJ8BqTMYE3y67YmshpF+NQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmlxfhscaexxqeaw59aqc66r2qce2suxge537pm7rtc8w7glp98s9xgny7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZFc1Vk9KTWhLU21Eeksx
            Wmd1aFpTcTM3UW45Zk1WVEFpSGtReFZsNGhVCkxCNy9zenRtdXlkU2dpYkpMREtK
            aGZ6eGE1emhab1Zic3pySnNvMmllbG8KLS0tIENEN3BKODVmQ1hQKzRzTFhkYlQv
            UWQ3SjZSRms3YWtaSmQ0V1V1TS9nU2MKLkJU3WNCMlBm4uU6EBcs2dIdKBQRdwwJ
            e/2RlPK3vaAK4HPx9vQYwsODbBTRRRnI53UD8ZKSad6L1D79f/QK2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103m56fylzmgf4j39kxnvyn0tarfxvtzmfxafj227pxn43z0rcgtqnfgfpz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdEFLdU5CWVFiU2FCZlRT
            M2J5bHpLQ3RBdm1nbkNiek44aWRCaWFlRlg0CkZ6L20zSGRMUDY3TkJSdlNBNTdi
            TC9Za2xoSytYcUh0dDlBcGdpTnF1RVEKLS0tIG91cXlrakU3K0YyZURaZXpYYXU4
            cE81WXA0QlcrckdnU2FNRkxQZ1VhLzAKrRpiebNr7EI2x57grwZQ9HrrGUF8Lp92
            HkwX+tT7KtbP8RFqQpCcmOdH8GwAbYwBnQi4x68adygV9a+HqnPytQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T21:27:10Z"
    mac: ENC[AES256_GCM,data:m0SQQnv+HVlzRoSA1CBdTKvFS7u/tgqO93s1ieTCHJfIJOBula0WATc09Vjpe7KUkhkl+9ObTb/oWv5wdDJRCVPm6iD97B0GhV5KN74R5gyQZUsMqha4dpsD1elJlkO8cHegehYuhpIizsr5bHXVCr9ydByuJhvXHRdzcGsiw8I=,iv:LhJYru0IfqqKqY8LX+kv3FYUERsViYMqU8yrRu9hIog=,tag:DWB2O4IfCT+m2gAvw5TrEg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.9.4
