apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Pour l'instant, on laisse cet index vide le temps de corriger l'erreur Flux.
# Nous listerons N8N et PostgreSQL ici dès que leurs manifestes seront prêts.