apiVersion: ENC[AES256_GCM,data:JdY=,iv:6lhoD3hku4OA0vO4BkBkmA0dDHQC5GiR+ssSRmeU478=,tag:VIkYmWvpw77IX/lY7wXLiQ==,type:str]
data:
    JWT_SECRET: ENC[AES256_GCM,data:ou71hV9QIUBiI5rEMf/iqNDg3AvVkBxB1zkA3LMp1r3drViSOGgOeUQHRzTsSUxS2GlytktnPHUiwqGZ,iv:hOdAaAe/SWWkEezETZsJt8NDfbQE8jS7mTcVSVMZPxM=,tag:cQSvCk5yOMpzkBC0O3gv4Q==,type:str]
    LLDAP_PASSWORD: ENC[AES256_GCM,data:iibMgvEWMC60Erab7BvdJw==,iv:khzs85FHP9kO2roXnUFdmlz6TTGgLLb0ceeDspedlUU=,tag:/txiwq58/JlAdCofGuZ6/w==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:yLWPrE+364irmvpb7oUBo/phcN3PwDTlm7BUPK2+NQuAlATnPUjcMru1JLHRpVIJYen7+SFLSA74O1j1,iv:otxA6N/U6vceA33IXzQRgHjPPF7ecdyL9eh2fvdXWn4=,tag:jXqpOtia0Ai9WQG9gX20Iw==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:ArAgFjyZZpVl/6/lcGw6ldclFC1jcgooVpYmktwcAYjOqeOVtA4c6kMGiaxQgkACb+Q+lozSEoQoOuhK,iv:58o1eeo6fVUVEAS9Y1lovw1XnJpp/JYYAycqCuR2rBE=,tag:yyjAkFUcupaVltuqgKKM9w==,type:str]
kind: ENC[AES256_GCM,data:bKJdSZVE,iv:YFdQ62qnxr/E1Hn0L7gMka2+M5tXZe/YH9eb8AQocv0=,tag:vJafRQ94FPDHd5OeS0d5ZA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:N8M/SJ7xGr+T0/r/caH2zw==,iv:FZLel/UINnudeHdix2k71DH4oQARXDhdSSdK4h3clXo=,tag:rL49Ijxoj/5NP1zrVYM1JA==,type:str]
    namespace: ENC[AES256_GCM,data:ShXwULecWg==,iv:Qu80bcDMSXcEBinU72qqQeldmFClP8ievEaAqjsIaX8=,tag:9v8Zx9CKzHGw6jdHw1ZZ7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmlxfhscaexxqeaw59aqc66r2qce2suxge537pm7rtc8w7glp98s9xgny7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K0ZnTHo0VUYwQTJLSkpp
            LzgzeDU1UmJFMzlOVzEwbGp6R21ZeGo3aUE0CjBtL2dJRjBpaGdSQmhjaVQxUkZH
            bVlJbVI0Wk9SUWtDRTBiajNvOU1HVGsKLS0tIDk0UHJKeHVQWG0wdXZGZ0p2Tkpm
            ODZSaWVBUHl1WmZzamZYV0N3b0ZHTTQKvyeKbugysKhiXG9d0kvpti1E9UYPxc1P
            jFV3WENxia10x66nNX3RyikN3PjgZbgUA2eDGIUT0XndQkjVQRelPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103m56fylzmgf4j39kxnvyn0tarfxvtzmfxafj227pxn43z0rcgtqnfgfpz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQnZOUnNzbFEvMFMzSXBx
            MnhoVysxRUprRzB5NitpVTUxT2J6WVlmU1NRCk1WQkNaWTcvWG1SMWlDZldWK0pG
            SHNGREVsK1Y2TmcyMkEwdTZIYzg1ZnMKLS0tIDJURXQyM3dWUUdGa2UxVjU3b1F0
            a3AzYmFsTzRUUUt4aGp2cXAwdVRZQTgKA/uh5ghkL1kUBqt9zm9aa30o0rNcW8lT
            ktYkwkGpKux26K9xf1+shbhGNmJTprlmd0QDsBaJKLrY4G4DYhv0LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-20T21:38:47Z"
    mac: ENC[AES256_GCM,data:vESGnkLnRD18O9XjtiIJ+yarfIdICsUHYHWvqaxXzI2/RUYNrRylmUOZafUY6uvDMbeJ3gyV2hBsYcL08T5pM4l4n7g4ximZ9urD3T57kLX5aPORlGhrHVf5eKrvKv1AW3fQ1ggE4KrpBnbbSFvIjaBSJwRmtErw+ITo4ec75mk=,iv:0iDOng+F2Y5eO6qIiehxUWbI/JAOSU1Oj4QD8XvV/yU=,tag:B8uTbsH45PBNajLoq4eXxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    mac_only_encrypted: true
    version: 3.9.4
